#!/bin/bash

PGPASSWORD=$5 psql -h $1 -U $3 $4 -c "
  insert into logs (action, affected_entity, details, user_id) values('create', 'everything', 'such detail', 1);
  insert into clients (name) values ('Nexen Energy');
  insert into clients (name) values ('Westcoast');
  insert into clients (name) values ('Repsol');
  insert into clients (name) values ('CPR Company');
  insert into clients (name) values ('Chevron Canada');
  insert into clients (name) values ('Encana');
  insert into clients (name) values ('Ensign');
  insert into clients (name) values ('Forever 21');
  insert into clients (name) values ('Inter Pipeline');
  insert into clients (name) values ('Keyera');
  insert into clients (name) values ('Pretium');
  insert into client_entities (client_id, company_code, lob_sector) values (1, '78GK', 'energy_natural_resources_oil_gas_upstream');
  insert into client_entity_jurisdictions (client_entity_id, jurisdiction) values (1, 'bc');
  insert into projects (name, client_id, lead_partner_id, lead_manager_id) values ('Nexen Energy 2017 IndTaxRA 2013-2016', 1, 18, 1);
  insert into projects (name, client_id, lead_partner_id, lead_manager_id) values ('Westcoast 2014 IndTaxRA 2010-2013', 2, 18, 1);
  insert into projects (name, client_id, lead_partner_id, lead_manager_id) values ('Repsol 2019 IndTaxRA 2017-2018', 3, 18, 1);
  insert into projects (name, client_id, lead_partner_id, lead_manager_id) values ('Repsol 2015 IndTaxRA 2013-2014', 3, 18, 1);
  insert into projects (name, client_id, lead_partner_id, lead_manager_id) values ('Repsol 2017 IndTaxRA 2015-2016', 3, 18, 1);
  insert into projects (name, client_id, lead_partner_id, lead_manager_id) values ('CPR Company 2019IndTaxRA 2016-2017', 4, 18, 1);
  insert into projects (name, client_id, lead_partner_id, lead_manager_id) values ('CPR Company 2016 IndTaxRA 2013-2015', 4, 18, 1);
  insert into projects (name, client_id, lead_partner_id, lead_manager_id) values ('Chevron Canada 2017 IndTaxRA 2013-2016', 5, 18, 1);
  insert into projects (name, client_id, lead_partner_id, lead_manager_id) values ('Encana 2017 IndTaxRA 2014-2016', 6, 18, 1);
  insert into projects (name, client_id, lead_partner_id, lead_manager_id) values ('Ensign 2017 IndTaxRA 2013-2016', 7, 18, 1);
  insert into projects (name, client_id, lead_partner_id, lead_manager_id) values ('Forever 21 2018 IndTaxRA 2014-2017', 8, 18, 1);
  insert into projects (name, client_id, lead_partner_id, lead_manager_id) values ('Inter Pipeline 2019 IndTaxRA 2015-2018', 9, 18, 1);
  insert into projects (name, client_id, lead_partner_id, lead_manager_id) values ('Keyera 2019 IndTaxRA 2014-2017', 10, 18, 1);
  insert into projects (name, client_id, lead_partner_id, lead_manager_id) values ('Pretium 2019 IndTaxRA 2015-2018', 11, 18, 1);
  insert into caps_gen (user_id, project_id, is_completed) values (1, 1, True);
  insert into caps_gen (user_id, project_id, is_completed) values (1, 1, True);
  insert into caps_gen (user_id, project_id, is_completed) values (1, 1, True);
  insert into fx_rates (date, usdtocad) values ('2010-01-01', 1.56);
  insert into fx_rates (date, usdtocad) values ('2010-01-02', 1.57);
  insert into user_project (user_id, project_id) values (1, 1);
  insert into gst_registration(caps_gen_id) values (1);

  update users set req_pass_reset = 'f';
  update users set is_superuser = 'y' where id = 1;
  update users set is_system_administrator = 'y' where id = 17;

  insert into user_project (user_id, project_id) values (2, 1);
  insert into user_project (user_id, project_id) values (3, 2);
  insert into user_project (user_id, project_id) values (3, 3);
  insert into user_project (user_id, project_id) values (4, 4);
  insert into user_project (user_id, project_id) values (4, 5);
  insert into user_project (user_id, project_id) values (4, 6);
  insert into user_project (user_id, project_id) values (5, 7);
  insert into user_project (user_id, project_id) values (6, 1);
  insert into user_project (user_id, project_id) values (7, 2);
  insert into user_project (user_id, project_id) values (8, 3);
  insert into user_project (user_id, project_id) values (8, 4);
  insert into user_project (user_id, project_id) values (8, 5);
  insert into user_project (user_id, project_id) values (9, 6);
  insert into user_project (user_id, project_id) values (10, 7);
  insert into user_project (user_id, project_id) values (10, 1);
  insert into user_project (user_id, project_id) values (11, 2);
  insert into user_project (user_id, project_id) values (11, 3);
  insert into user_project (user_id, project_id) values (11, 4);
  insert into user_project (user_id, project_id) values (12, 5);
  insert into user_project (user_id, project_id) values (13, 6);
  insert into user_project (user_id, project_id) values (13, 7);
  insert into user_project (user_id, project_id) values (14, 1);
  insert into user_project (user_id, project_id) values (14, 2);
  insert into user_project (user_id, project_id) values (14, 3);
  insert into user_project (user_id, project_id) values (15, 4);
  insert into user_project (user_id, project_id) values (16, 5);
  insert into user_project (user_id, project_id) values (16, 6);
  insert into user_project (user_id, project_id) values (17, 7);
  insert into user_project (user_id, project_id) values (17, 1);
  insert into user_project (user_id, project_id) values (17, 2);
  insert into user_project (user_id, project_id) values (18, 1);
  insert into user_project (user_id, project_id) values (18, 2);
  insert into user_project (user_id, project_id) values (18, 3);
  insert into user_project (user_id, project_id) values (18, 4);
  insert into user_project (user_id, project_id) values (18, 5);
  insert into user_project (user_id, project_id) values (18, 6);
  insert into user_project (user_id, project_id) values (18, 7);
  insert into user_project (user_id, project_id) values (18, 8);
  insert into user_project (user_id, project_id) values (18, 9);
  insert into user_project (user_id, project_id) values (18, 10);
  insert into user_project (user_id, project_id) values (18, 11);
  insert into user_project (user_id, project_id) values (18, 12);
  insert into user_project (user_id, project_id) values (18, 13);
  insert into user_project (user_id, project_id) values (18, 14);
  insert into user_project (user_id, project_id) values (1, 2);
  insert into user_project (user_id, project_id) values (1, 3);
  insert into user_project (user_id, project_id) values (1, 4);
  insert into user_project (user_id, project_id) values (1, 5);
  insert into user_project (user_id, project_id) values (1, 6);
  insert into user_project (user_id, project_id) values (1, 7);
  insert into user_project (user_id, project_id) values (1, 8);
  insert into user_project (user_id, project_id) values (1, 9);
  insert into user_project (user_id, project_id) values (1, 10);
  insert into user_project (user_id, project_id) values (1, 11);
  insert into user_project (user_id, project_id) values (1, 12);
  insert into user_project (user_id, project_id) values (1, 13);
  insert into user_project (user_id, project_id) values (1, 14);
"
