#!/bin/bash

PGPASSWORD=$5 psql -h $1 -U $3 $4 -c "
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'bkpf_belnr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'doc_type_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'inv_date');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'post_date_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'bkpf_bukrs_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'bkpf_gjahr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'fx_rate');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'bkpf_kzwrs_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'fiscal_period_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'trnx_code_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'ccy');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'inv_num');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'bsak_augbl_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'bsak_augdt_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'bsak_belnr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'bsak_bukrs_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'bsak_buzei_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'bsak_gjahr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'bsak_lifnr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'spec_trnx_type_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'spec_indicator_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'cash_disc_percent_1_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'cash_disc_days_1_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'cash_disc_percent_2_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'cash_disc_days_2_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'pymt_period_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'pymt_terms_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'assign_num_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'main_asset_num');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'asset_sub_num');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'gl_doc_num');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'post_key_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'gl_doc_status');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'bseg_budat_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'co_code_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'bseg_buzei_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'amount_local_ccy');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'po_doc_num');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'bseg_ebelp_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'func_area_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'fiscal_year_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'bus_area_dept_num_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'largest_debit_half_acct_num_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'control_area_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'cost_ctr_num_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'cx_num');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'vend_num');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'material_num_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tax_type_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'bseg_mwsk3_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'po_tax_code_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'gst_hst_qst_pst_local_ccy');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'bseg_pargb_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'profit_ctr_num');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'wbs_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'item_descr_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'reverse_doc_num');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'reverse_reason_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tax_jur_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'sales_doc_num_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'billing_doc_num');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'gst_hst_pst_qst_doc_ccy');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'ap_ar_amt_doc_ccy');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'cepc_datbi_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'cepc_kokrs_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'cepc_prctr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'profit_ctr_tx_jur');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'profit_ctr_name');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'profit_ctr_descr');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'cepct_prctr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'cepct_spras_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'csks_datbi_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'csks_kokrs_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'csks_kostl_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'cost_ctr_tx_jur');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'cskt_datbi_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'cskt_kokrs_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'cskt_kostl_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'cost_ctr_name');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'cost_ctr_descr');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'cskt_spras_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'ska1_bukrs_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'ska1_ktopl_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'ska1_saknr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'skat_ktopl_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'skat_saknr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'skat_spras_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'lrg_deb_1_acct_num_gl_lrg_deb_2_acct_num_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'skb1_bukrs_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'skb1_saknr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t003t_blart_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'doc_type_descr');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t003t_spras_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tbslt_bschl_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'post_key_descr');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tbslt_spras_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tbslt_umskz_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'ccy_descr');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tcurt_spras_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tcurt_waers_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tgsbt_gsber_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'bus_area_dept_name_gl');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tgsbt_spras_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'ekko_ebeln_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'punch_grp_po');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'punch_org_po');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'handover_loc_po');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'vend_phone');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'vend_person');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'wbs_po');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'ekpo_ebeln_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'ekpo_ebelp_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'ekpo_ematn_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'ekpo_lgort_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'po_tx_code_po');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'plant_num');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'po_tx_jur');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'po_item_descr');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'lfa1_land1_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'lfa1_lifnr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'vend_name');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'vend_city');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'vend_region');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'vend_tax_num_1');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'vend_tax_num_2');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'vend_tax_num_3');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'vend_tax_num_4');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'vend_tax_num_5');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'vend_tax_num_type');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'vend_reg_num');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'lfas_land1_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'lfas_lifnr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'lfm1_ekorg_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'incoterms1');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'incoterms2');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'lfm1_lifnr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t024_ekgrp_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'purch_group_descr_po');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t024e_ekorg_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'purch_org_descr_po');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'toa01_arc_doc_id_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'toa01_archiv_id_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'toa01_object_id_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'toa01_sap_object_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mat_descr_mat');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'makt_matnr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'ean_upc_num_mat');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mara_gewei_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mat_orig_ctry_mat');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mara_magrv_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mara_matkl_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mara_matnr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mara_mfrnr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'ean_categ_mat');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mat_tx_class_mat');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mara_voleh_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mat_dept_ctry_mat');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mlan_matnr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mat_tx_ind_mat');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mseg_ebeln_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mseg_ebelp_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mat_doc_num_mat');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mseg_mjahr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mat_plnt_mat');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mseg_zeile_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'stor_loc_desc_mat');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'stor_loc_mat');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'stor_plant_mat');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t006a_msehi_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t006a_spras_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t023t_matkl_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t023t_spras_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mat_group_descr_mat');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tmkm1t_land1_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tmkm1t_spras_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mat_tx_ind_descr_mat');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'ean_categ_descr_mat');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tntpb_numtp_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tntpb_spras_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tskmt_spras_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tskmt_tatyp_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tskmt_taxkm_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'mat_tx_class_descr_mat');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tvegrt_spras_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tvtyt_spras_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tvtyt_traty_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'proj_descr_proj');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'proj_defin_proj');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'proj_internal_proj');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'proj_tx_jur_proj');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'proj_mngr_name_proj');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'proj_mngr_num_proj');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'bus_area_proj');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'plant_proj');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'object_num_proj');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'jv_obj_type_proj');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'wbs_bus_area_proj');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'wbs_cntrl_area_proj');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'wbs_elem_id_proj');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'wbs_elem_descr_proj');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'proj_type_proj');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'prps_psphi_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'prps_pspnr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'proj_loc_proj');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'check_num_pmt');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'payr_hbkid_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'payr_rzawe_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'pymt_dt_pmt');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'payr_zbukr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'pymt_doc_num_pmt');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'regup_bukrs_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'regup_buzei_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'regup_ebeln_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'regup_ebelp_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'payee_code_pmt');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'regup_gjahr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'regup_hkont_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'cx_num_pmt');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'regup_laufd_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'regup_laufi_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'regup_lifnr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'regup_saknr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'regup_vblnr_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'regup_xvorl_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'co_code_pmt');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'regup_zlsch_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t042zt_land1_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t042zt_spras_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'pymt_method_pmt');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t042zt_zlsch_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'j_1atodct_j_1atodct_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'j_1atodct_spras_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tx_type_descr_tx');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t005s_bland_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'prov_tx_code_tx');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t005s_land1_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t007a_kalsm_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t007a_mwskz_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t007s_kalsm_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t007s_mwskz_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t007s_spras_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tx_name_tx');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'ttxjt_kalsm_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'ttxjt_spras_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tx_jur_descr_tx');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'ttxjt_txjcd_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t001_bukrs_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'co_name');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t001_land1_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'plant_name_plant');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'plant_tx_jur_plant');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t001w_werks_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t005t_land1_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'cntry_name');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'t005t_spras_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'incoterms1_descr');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tinct_inco1_key');
  INSERT INTO data_mappings(caps_gen_id,cdm_label_script_label) VALUES (2,'tinct_spras_key');
  INSERT INTO sap_aufk(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_bkpf(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_bsak(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_bsak(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
  INSERT INTO sap_bseg(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
  INSERT INTO sap_bseg(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_cepct(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
  INSERT INTO sap_cepct(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_csks(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
  INSERT INTO sap_csks(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_cskt(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
  INSERT INTO sap_cskt(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_ekko(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
  INSERT INTO sap_ekko(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_ekpo(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
  INSERT INTO sap_ekpo(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_iflot(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
  INSERT INTO sap_iflot(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_iloa(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
  INSERT INTO sap_iloa(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_lfa1(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
  INSERT INTO sap_lfa1(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_makt(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
  INSERT INTO sap_makt(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_mara(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
  INSERT INTO sap_mara(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_payr(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
  INSERT INTO sap_payr(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_proj(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
  INSERT INTO sap_proj(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_prps(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
  INSERT INTO sap_prps(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_regup(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
  INSERT INTO sap_regup(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_skat(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
  INSERT INTO sap_skat(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_t001(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
  INSERT INTO sap_t001(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_t007s(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
  INSERT INTO sap_t007s(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_skb1(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
  INSERT INTO sap_skb1(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"tomato\",\"color\": \"red\"}');
  INSERT INTO sap_t003t(caps_Gen_id, data) VALUES (2,'{\"vegie\": \"potato\",\"color\": \"brown\"}');
"
