#!/bin/bash

PGPASSWORD=LHDEV1234 psql -h localhost -U itra itra_db -c "
  INSERT INTO codes(code_number, description) VALUES (101, 'Missed ITC');
  INSERT INTO codes(code_number, description) VALUES (102, 'Missed ITR');
  INSERT INTO codes(code_number, description) VALUES (103, 'Missed ITC & ITR');
  INSERT INTO codes(code_number, description) VALUES (104, 'Missed ITC/ITR - GST/HST/QST Self Assessed In Error');
  INSERT INTO codes(code_number, description) VALUES (105, 'Missed ITC/ITR - Short Paid');
  INSERT INTO codes(code_number, description) VALUES (109, 'ITC/ITR recovery identified internally');
  INSERT INTO codes(code_number, description) VALUES (110, 'BC Exempt / Consumed Out of Province');
  INSERT INTO codes(code_number, description) VALUES (111, 'BC Production Machinery & Equipment');
  INSERT INTO codes(code_number, description) VALUES (112, 'BC Self Assessed In Error');
  INSERT INTO codes(code_number, description) VALUES (119, 'BC PST recovery identified internally');
  INSERT INTO codes(code_number, description) VALUES (120, 'MAN Exempt / Consumed Out of Province');
  INSERT INTO codes(code_number, description) VALUES (121, 'MAN Self Assessed In Error');
  INSERT INTO codes(code_number, description) VALUES (129, 'MAN PST recovery identified internally');
  INSERT INTO codes(code_number, description) VALUES (130, 'SASK Exempt / Consumed Out of Province');
  INSERT INTO codes(code_number, description) VALUES (131, 'SASK Self Assessed In Error');
  INSERT INTO codes(code_number, description) VALUES (139, 'SASK PST recovery identified internally');
  INSERT INTO codes(code_number, description) VALUES (140, 'Other PST Recovery');
  INSERT INTO codes(code_number, description) VALUES (149, 'Other PST recovery identified internally');
  INSERT INTO codes(code_number, description) VALUES (150, 'Duplicate Payment');
  INSERT INTO codes(code_number, description) VALUES (151, 'Overpayment');
  INSERT INTO codes(code_number, description) VALUES (159, 'Overpayment recovery identified internally');
  INSERT INTO codes(code_number, description) VALUES (201, 'No $ based on invoice review');
  INSERT INTO codes(code_number, description) VALUES (202, 'No $ based on vendor testing');
  INSERT INTO codes(code_number, description) VALUES (203, 'No $ not material (GST/QST/PST)');
  INSERT INTO codes(code_number, description) VALUES (204, 'No $ statute barred (GST/QST/PST)');
  INSERT INTO codes(code_number, description) VALUES (205, 'Unlikely recovery based on vendor location');
  INSERT INTO codes(code_number, description) VALUES (206, 'Unlikely recovery based on vendor nature');
  INSERT INTO codes(code_number, description) VALUES (207, 'No opportunity based on PY review');
  INSERT INTO codes(code_number, description) VALUES (208, 'Taxes/Premiums/Royalties');
  INSERT INTO codes(code_number, description) VALUES (209, 'Financial Transactions');
  INSERT INTO codes(code_number, description) VALUES (210, 'Sponsoship/Donations');
  INSERT INTO codes(code_number, description) VALUES (211, 'In and out (reversal) no $');
  INSERT INTO codes(code_number, description) VALUES (212, 'No $ - Intercompany Transactions');
  INSERT INTO codes(code_number, description) VALUES (221, 'Pare down');
  INSERT INTO codes(code_number, description) VALUES (230, 'Scoped out by client');
  INSERT INTO codes(code_number, description) VALUES (250, 'Exposures');
  INSERT INTO codes(code_number, description) VALUES (301, 'Investigate further');
  INSERT INTO codes(code_number, description) VALUES (302, 'No Image/Image issue - investigate further');
  INSERT INTO codes(code_number, description) VALUES (303, 'Employee expense report');
  INSERT INTO codes(code_number, description) VALUES (304, 'Intercompany transactions');
  INSERT INTO codes(code_number, description) VALUES (305, 'Suspense/Clearing/Accruals');
  INSERT INTO codes(code_number, description) VALUES (306, 'Statement/Cheque Request Only');
  INSERT INTO codes(code_number, description) VALUES (307, 'Pass-through GST/HST/QST included in reimbursement');
  INSERT INTO codes(code_number, description) VALUES (308, 'Purchasing Cards');
  INSERT INTO codes(code_number, description) VALUES (309, 'Deposit');
  INSERT INTO codes(code_number, description) VALUES (301, 'Settlement/Damage/Termination Payments');
  INSERT INTO codes(code_number, description) VALUES (311, 'Call vendor');
  INSERT INTO codes(code_number, description) VALUES (312, 'Ask Client');
  INSERT INTO codes(code_number, description) VALUES (500, 'Priority for pulling');
  INSERT INTO codes(code_number, description) VALUES (501, 'Pull second');
  INSERT INTO codes(code_number, description) VALUES (502, 'Pull third');
"
