"""empty message

Revision ID: d79c9ee1b2ac
Revises:
Create Date: 2019-05-02 11:26:40.711093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79c9ee1b2ac'
down_revision = None
branch_labels = None
depends_on = None

def seed_data():
    test_table = sa.sql.table('exercises', sa.sql.column('name', sa.String), sa.sql.column('quantity', sa.Float), sa.sql.column('unit', sa.String))
    op.bulk_insert(
        test_table,
        [
            {'id': 1, 'name': 'bicycle crunches', 'quantity': 10, 'unit': 'count' },
            {'id': 2, 'name': 'calf raises', 'quantity': 10, 'unit': 'count' },
            {'id': 3, 'name': 'crunch', 'quantity': 10, 'unit': 'count' },
            {'id': 4, 'name': 'high knees', 'quantity': 10, 'unit': 'count' },
            {'id': 5, 'name': 'leg raises (both)', 'quantity': 10, 'unit': 'count' },
            {'id': 6, 'name': 'leg raises (lateral <each side>)', 'quantity': 10, 'unit': 'count' },
            {'id': 7, 'name': 'lunges (forward <each leg>)', 'quantity': 10, 'unit': 'count' },
            {'id': 8, 'name': 'lunges (reverse <each leg>)', 'quantity': 10, 'unit': 'count' },
            {'id': 9, 'name': 'lunges (side <each side>)', 'quantity': 10, 'unit': 'count' },
            {'id': 10, 'name': 'mountain climbers', 'quantity': 10, 'unit': 'count' },
            {'id': 11, 'name': 'plank (front)',  'quantity': 1, 'unit': 'minute' },
            {'id': 12, 'name': 'plank (side <each>)', 'quantity': 30, 'unit': 'seconds' },
            {'id': 13, 'name': 'plank ups', 'quantity': 10, 'unit': 'count' },
            {'id': 14, 'name': 'pushup (diamond)', 'quantity': 10, 'unit': 'count' },
            {'id': 15, 'name': 'pushup (normal)', 'quantity': 10, 'unit': 'count' },
            {'id': 16, 'name': 'pushup (wide)', 'quantity': 10, 'unit': 'count' },
            {'id': 17, 'name': 'squat (normal)', 'quantity': 10, 'unit': 'count' },
            {'id': 18, 'name': 'squat (sumo)', 'quantity': 10, 'unit': 'count' }
        ]
    )

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('compliance_hits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('failtype', sa.String(length=25), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('exercise', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['exercise'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    seed_data()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compliance_hits')
    op.drop_table('exercises')
    # ### end Alembic commands ###
